### ISSUE TITLE
Set proper container keys when event is created inside of an event

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#104]
Notifications need their Reminder container key and their lifestyle container key set when their created inside an event i.e. not unsorted. Reminder needs its Lifestyle container key set.

**Comment by JoetheSoda** [comment]
Doesn't this do this already. Whats going wrong with it?

**Comment by JDNdeveloper** [comment]
It looks like it does. Just thoroughly test that it does it for all event
types and then close it.

**Comment by JDNdeveloper** [comment]
When you add a notification inside of a reminder does it set both container
keys? The parent lifestyle and parent reminder?

**Comment by JoetheSoda** [comment]
yes it does
