### ISSUE TITLE
Link settings button to setting page

### ISSUE THREAD

**Issue by agonza26** [JDNdeveloper/Off-By-One#109]
Once I complete the settings page, or have something basic, and its committed just link the icon to the page, I will comment on this page and in hangouts when it is done

**Comment by JDNdeveloper** [comment]
Okay, cool. Just let me know and I'll get it done as soon as I can so you can test it.

**Comment by agonza26** [comment]
im going to name the activity SettingsActivity.java, and the xml is activity_settings.xml,

**Comment by JDNdeveloper** [comment]
Implemented. Currently commented out since SettingsActivity is not functional yet. @agonza26, just uncomment it to test.
