### ISSUE TITLE
Check Tic Tac Toe game to see how I did settings page there, tell Alex

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#111]

**Comment by JDNdeveloper** [comment]
@agonza26, do you need this anymore?

**Comment by JDNdeveloper** [comment]
Settings  is implemented already.

**Comment by agonza26** [comment]
@JDNdeveloper wait, what was this?

**Comment by JDNdeveloper** [comment]
This was just a reminder to me to look at a previous app of mine to see how I did settings in that app.
