### ISSUE TITLE
Work on Final Presentation

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#134]

**Comment by KevinCCheng** [comment]
Created presentation template and filled a good chunk of the things we need in the presentation. Now it needs for the rest of the presentation to be finished and reviewed before submitting.

**Comment by KevinCCheng** [comment]
Also, I think this has to be done before Tuesday. Since we are presenting to the class.

**Comment by JDNdeveloper** [comment]
It's basically done. I'm leaving it open for now in case anyone wants to add more to it. I just followed Jullig's template.

**Comment by JDNdeveloper** [comment]
Since no one else has edited it or even looked at it...I'm going to mark this as completed.
