### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#142]

**Comment by agonza26** [comment]
still deciding on a single assignee, but Im thinking this could be a group effort

**Comment by KevinCCheng** [comment]
Duplicate Ticket: https://github.com/JDNdeveloper/Off-By-One/issues/134

**Comment by JDNdeveloper** [comment]
Make sure that the one that we're keeping is assigned to the proper
milestone

**Comment by KevinCCheng** [comment]
Closed due to duplicate ticket #134
