### ISSUE TITLE
Make Scrollviews of events full screen

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#15]

**Comment by JohnGemignani** [comment]
This can be done. However, I don't feel it is necessary to do it right now or make a separate task. We are going to be adjusting a lot on the adapters and UI tweaks will be part of that. Closing for now.

**Comment by JDNdeveloper** [comment]
I don't think we should close issues just because we don't want to work on them currently. If we close them then we'll forget about them.

**Comment by JDNdeveloper** [comment]
I will take this on. Don't worry about it.

**Comment by JDNdeveloper** [comment]
@agonza26 This is something you could do as well.

**Comment by agonza26** [comment]
@JDNdeveloper 
so right now I removed the margins so that it looks as though when you scroll it goes behind the action bar, is that what you want? i'll commit to my branch and show you what it is

**Comment by JDNdeveloper** [comment]
I don't want it to be behind the action bar. Pretend that the white area beneath the action bar is the entire screen. I just want it to fill that area, not any other area. Currently it doesn't cover that whole space. I want it just to cover that space, not hide behind anything, but completely cover that space.

**Comment by agonza26** [comment]
i still dont think i understand what you mean by cover, right now its not behind the action bar, it stops right underneath it.  are you saying the  action bar should scroll with the page? or do you want the text to reach edge to edge?

**Comment by JDNdeveloper** [comment]
I think you have it the way I have in mind. I'll confirm later tonight.

**Comment by JDNdeveloper** [comment]
I think this has been accomplished.
