### ISSUE TITLE
Sound does not work

### ISSUE THREAD

**Issue by JoetheSoda** [JDNdeveloper/Off-By-One#153]
Whoever is in charge of Action needs to test some stuff, because when I set an action to have sound, it does not play when the notification goes off. I cannot test vibration, so I don't know if that works either.

**Comment by JDNdeveloper** [comment]
This is my area, I'll figure it out.

**Comment by JDNdeveloper** [comment]
Tested and Notification.java, Action.java, and Phone.java are not at fault. Reassigning to Josh to take a look at other possible causes.
