### ISSUE TITLE
Change logo to match color scheme, or vice-versa

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#16]

**Comment by KevinCCheng** [comment]
Please define colors used in the app or define a color to use.

**Comment by JDNdeveloper** [comment]
This is a long term thing. It needs to be done after we as a group decide
on the color scheme. It doesn't need to be done right now.

**Comment by KevinCCheng** [comment]
Ok, I have the original project document that allows changes in 3 seconds.

**Comment by JDNdeveloper** [comment]
What do you mean?

**Comment by KevinCCheng** [comment]
Nothing for you to worry about.

**Comment by JDNdeveloper** [comment]
I think this is good now.
