### ISSUE TITLE
Gray out switch in event activies when a container is disabled

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#167]
Just look at my adapter code

**Comment by JDNdeveloper** [comment]
Currently in the reminder adapter or the notification adapter the switch isn't grayed out when the containers are disabled. Just look at my switch code in the reminder adapter or the notification adapter to see how to properly do it.

**Comment by JoetheSoda** [comment]
For the notification and reminder in notification and reminder respectively

**Comment by JoetheSoda** [comment]
Complete
