### ISSUE TITLE
See if navbar can be shortened (maybe unwanted)

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#17]

**Comment by KevinCCheng** [comment]
It looks like it can be changed. You need to change "android:layout_width="match_parent"" in Relative Layout XML String in fragment_navagation_drawer.xml.

I tried to change it from "match parent" to specific size, but the emulator is not seeing the difference. 

Can someone double check with a physical device for me. 
![2-6-2015 5-53-47 pm](https://cloud.githubusercontent.com/assets/9097368/6090310/284016fa-ae29-11e4-8083-a89755d55332.png)

**Comment by KevinCCheng** [comment]
Found another unspecified area where it is actually set. it is in /res/values/demens.xml/dimens.xml.

<dimen name="navigation_drawer_width">240dp</dimen>

This is the exact location to update. 


NOTE:
