### ISSUE TITLE
Implement when switch is toggled to enabled, set all alarms. Look at how the adapters do this when the switch is toggled.

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#172]

**Comment by JDNdeveloper** [comment]
Make sure to use my LifestyleAdapter code as reference for the LifestyleActivity and my ReminderAdapter as reference for the ReminderAdapter. DO NOT use the code from one of the adapters from both.

**Comment by JoetheSoda** [comment]
Do I need to disable them when the switch is turned off?

**Comment by JDNdeveloper** [comment]
What do you mean? Just copy my code exactly. Also, get on hangouts so we
can chat.

**Comment by JoetheSoda** [comment]
I realized what I asked doesn't make sense, the issue has been fixed

**Comment by JDNdeveloper** [comment]
To answer your question. No, don't disable them when it's switched off
