### ISSUE TITLE
Create custom ic_drawer.png (name it something else)

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#20]

**Comment by JDNdeveloper** [comment]
Preferably a white icon

**Comment by KevinCCheng** [comment]
Done, updated XML also 

Images can be seen at \Off-By-One\LifeReminders\app\src\main\res\@drawable

**Comment by JDNdeveloper** [comment]
What XML needed to be changed? The only code that needed to be edited was in the fragment java code I thought.

**Comment by KevinCCheng** [comment]
Did not want to override the default image.
