### ISSUE TITLE
Create custom onPressed icon for settings

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#21]

**Comment by JDNdeveloper** [comment]
This allows us to show what the setting button looks like when the user clicks on. This is usually some sort of highlight or shadow behind the icon.

**Comment by JDNdeveloper** [comment]
After you create it, just add it to the XML code where the setting button is under the android:onpressed (something like that) tag.

**Comment by KevinCCheng** [comment]
The xml code needs to be changed from ImageButton to Selector http://www.mkyong.com/android/android-imagebutton-selector-example/

**Comment by JDNdeveloper** [comment]
It doesn't. I've worked with this before and can make it work. I'll add it
tomorrow morning.
