### ISSUE TITLE
Rework notification icon

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#22]
I like the idea of a white notification icon, but I feel like the current one has the "LR" part too small.

**Comment by KevinCCheng** [comment]
LR part is now bigger, check it first before closing

**Comment by JDNdeveloper** [comment]
It looks good. The only change is that I would get rid of the shadow behind the top of the R. It makes it hard to see the L. So just have the shadows below the letters.

**Comment by KevinCCheng** [comment]
Check if this is what you want.

**Comment by JDNdeveloper** [comment]
Perfect.
