### ISSUE TITLE
Create plus button, check to see if built-in to android

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#23]

**Comment by KevinCCheng** [comment]
See http://www.google.com/design/spec/components/buttons.html#buttons-usage

**Comment by KevinCCheng** [comment]
Google may have something built in http://stackoverflow.com/questions/24459352/how-can-i-add-the-new-floating-action-button-between-two-widgets-layouts

**Comment by JDNdeveloper** [comment]
Okay cool. Can you experiment around to see if we can implement it?

**Comment by KevinCCheng** [comment]
Looking at the example Google has in Android Studio, you can, but it will require some amount of rework into the code.

**Comment by JDNdeveloper** [comment]
Okay. We should discuss this with the group on Monday.

**Comment by KevinCCheng** [comment]
Code is in FloatingActionButtonBasic.zip file to be implemented.

**Comment by KevinCCheng** [comment]
For some reason, the button works as intended if the XML item is a button. But once we change it to a ImageButton, the button stops functioning. 

Temporarily set the plus button to a standard button so that we can work on it.

**Comment by KevinCCheng** [comment]
Button Works now. 

Found solution
