### ISSUE TITLE
Drawer two icon needs to look exactly like drawer in terms of positioning

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#24]

**Comment by KevinCCheng** [comment]
Just made color changes to the exact drawer they gave.

**Comment by JDNdeveloper** [comment]
Huh. The default one is centered bottom left and drawer two is centered in
the middle.

**Comment by JDNdeveloper** [comment]
The centering matters.

**Comment by KevinCCheng** [comment]
Well, all I did now was just changed the colors of those bars Google gave, there was no additions I made except for the color.

**Comment by JDNdeveloper** [comment]
Does the app compile and look okay with the new navigation button?

**Comment by KevinCCheng** [comment]
Yes.

**Comment by JDNdeveloper** [comment]
Okay, cool
