### ISSUE TITLE
Change settings onpressed to grey circle

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#25]
Hey Kevin, I got the settings working when pressed but it's looking a little weird. Because of the larger graphic it looks like it's jumping out at you when you press it and it seems a little off-putting. Check it out for yourself and see what you think. I think it would be nice if the on-pressed background image was just a grey circle that was the same color as the current onpressed image. So when you click on settings it just shows a little grey background solid circle behind the settings icon.

**Comment by JDNdeveloper** [comment]
Since it's already implemented, you can just overwrite the current graphics and it will appear in the app when you click the settings button.

**Comment by KevinCCheng** [comment]
Fixed to have correct dimensions
