### ISSUE TITLE
Rework flat logo

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#28]
Hey Kevin. I like the flat logo, but it looks like the LR is a little off-center. I think this might be because of the shadows that were there before. 

Also, could you add a light border around the edges so that the LR pops a little bit more. Not so much to make it 3D, but enough that it stands out sharply against the red background.

Thanks.

**Comment by KevinCCheng** [comment]
Check if this is what you want.

**Comment by JDNdeveloper** [comment]
Something still doesn't seem right to me. Did you center the LR part of the
graphic? I'll switch the app to use the flat icon temporarily and you can
take a look after merging down.

**Comment by JDNdeveloper** [comment]
It looks like there's a little problem with the top of the circle. It seems a little blurry.

**Comment by KevinCCheng** [comment]
Then there will be no border

**Comment by JDNdeveloper** [comment]
Take a look at the logo in the app and tell me what you think.

**Comment by KevinCCheng** [comment]
If you want flat sharp, then I can't add a light border around the edges

**Comment by JDNdeveloper** [comment]
That's fine. All I'm talking about is centering (shifting down) the LR
inside of the circle and also fixing the top pixels of the circle that seem
to be a little messed up. We can discuss this on Monday if that works
better.

**Comment by KevinCCheng** [comment]
Done
