### ISSUE TITLE
Fix the code so that the correct logo size is used

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#33]
In the upper right hand icon and in the notification bar, make sure that the correct logo size is used to avoid the edge pixelation.

**Comment by JDNdeveloper** [comment]
@agonza26 would you be comfortable tackling this? If so, just assign yourself to it.

**Comment by agonza26** [comment]
@JDNdeveloper do you have an image of what the edge pixelation looks like so that I can get an understanding of what to do, I dont see anything wrong on my device

**Comment by JDNdeveloper** [comment]
@agonza26 How is this going?

**Comment by JDNdeveloper** [comment]
Was this figured out or did you just close it? In the future, it's good to
give a comment when you close an item that states that the feature has
either been implemented or has been abandoned and why.
