### ISSUE TITLE
Default calendar value

### ISSUE THREAD

**Issue by JohnGemignani** [JDNdeveloper/Off-By-One#37]
Please create a default calendar value on initial object creation. This is needed to test Gson and to test for uninitialized cases. This is similar to the default values for name and key.

**Comment by JDNdeveloper** [comment]
This should be done in storage, not in the actual event class. That's the whole point of storage handling the test events, so that the actual classes don't hard code in stuff we'll need to change later.

**Comment by JDNdeveloper** [comment]
Sorry, not storage to test GSON. What I should have said was that the GSON tester should set the test Calendar of the Notification object.

**Comment by JDNdeveloper** [comment]
Fine, I'll add a dummy default Calendar to the Notification object when I have time.

**Comment by JDNdeveloper** [comment]
I made it so that by default all notification have a calendar that is set to 23:59:59 on January 1st 2000. So if when GSON builds the notification, and that's the calendar it generates inside of Notification, we're golden.
