### ISSUE TITLE
Get Phone Class functions defined

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#4]
Hey Alex @agonza26. I was wondering if you wanted to work on the Phone Class. Basically it houses a bunch of functions that use built-in features of the phone, like vibrate, ring, etc. Let me know if you want to pursue this, want someone to work with you on this, or would prefer to have this be assigned to someone else.

**Comment by agonza26** [comment]
I can work on this unless you want me to work on something else! we can discuss tomorrow what methods I should add

**Comment by JDNdeveloper** [comment]
The methods are already in there. The class is created. The functions just
need to be implemented.
