### ISSUE TITLE
Work on "Add New" pages

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#42]

**Comment by JDNdeveloper** [comment]
Just a couple of things, we should try to aim for the action bar to carry over to the new activities
Also, I was thinking of having the enabled button to the right of the editable field to reduce space
And I don't think we need it to have the textfield that says "enabled". I think it's pretty self explanatory what the toggle is for

**Comment by agonza26** [comment]
@JoshInnis @JoetheSoda if this still needs work, I can take this task
