### ISSUE TITLE
Make sure when navigating back from an Event that you return to proper fragment

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#51]

**Comment by JDNdeveloper** [comment]
Make sure correct item is selected in nav bar and action bar color is correct as well.

**Comment by JDNdeveloper** [comment]
Make sure these happen:
1. change status bar and action bar color. 
2. Make sure nav bar selection is correctly highlighted. 
3. Make sure plus button will direct to correct place. 
4. Make sure action bar text is correct. 
5. Make sure correct array adapter is loaded.

**Comment by agonza26** [comment]
@KevinCCheng, make sure to talk to @JoetheSoda about how he set up the constant that stores which page you are on as well as anything else you need to know about this task

**Comment by KevinCCheng** [comment]
So, Android has a built in stack that keeps track on where it is. The hardware back button does this right but out regular back button doesn't follow it. 

We should either make the status bar back button simulate the hardware back button or just remove it if it is not working.

**Comment by JDNdeveloper** [comment]
Hey Kevin. Actually the back arrow doesn't currently do what we want it to
do. We want it to return to the proper fragment in main which it currently
doesn't do. Instead it always returns to all lifestyles.

**Comment by JDNdeveloper** [comment]
Oh wow. Didn't even try the hardware back button. You're right.

Anyways, the thing that we should be doing is forcing the app to load the
proper fragment each time main is called by using the fragmentLocation
variable.

**Comment by JDNdeveloper** [comment]
Kevin,

I'm pretty sure I know what needs to happen if you want to reassign this
task to me.

Up to you.

**Comment by JDNdeveloper** [comment]
http://stackoverflow.com/q/12276027/903996

**Comment by JDNdeveloper** [comment]
Implemented.
