### ISSUE TITLE
Make plus button shadow off center, focused towards bottom of icon

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#54]
Take a look at the gmail app to see how it's done.

**Comment by JDNdeveloper** [comment]
Just a note, currently the shadow seems to be focused on the lower right side, when according to the google standard the shadow should be evenly focused on the entire lower portion, not leaning towards a particular side. Also, the gmail app shadow is very light. I think currently the shadow is a little too dark for what we're trying to accomplish, which is a hovering effect.

**Comment by JDNdeveloper** [comment]
Also, I think the icon should be a little smaller per the gmail plus button.

**Comment by KevinCCheng** [comment]
Check it now.....

**Comment by KevinCCheng** [comment]
Button updated to spec
