### ISSUE TITLE
Get rid of all debugging toast messages before release

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#56]
@JoetheSoda @KevinCCheng @agonza26 @JohnGemignani. Just a reminder to remove these before the final release. You might even consider just replacing these with Log statements since they can do the same thing and the user never sees a Log statement.

**Comment by JoetheSoda** [comment]
Some of my toast statements I want to stay. I will put a comment above those specifying which they are. So don't just delete all the Toasts in the code

**Comment by KevinCCheng** [comment]
Removed certain toast message that were allowed to be commented out. Replaced the toast messages with either Log.e and log.i

**Comment by JDNdeveloper** [comment]
Reopened so that I can work on removing my toasts.

**Comment by JDNdeveloper** [comment]
I'm pretty sure I got rid of mine.I'm passing on the baton to Alex.

**Comment by agonza26** [comment]
don't have any toast messages so im going to assign this to john now

**Comment by JohnGemignani** [comment]
Made into a first time start up message.
