### ISSUE TITLE
Link plus button to add new page, pass in info

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#64]
The add new activity will need to have context, aka know where it's coming from.

**Comment by KevinCCheng** [comment]
Pushing this off since the corresponding XML are not ready yet by other open tickets.

**Comment by JDNdeveloper** [comment]
That's fine, I just issued it preemptively since it will eventually need to
be handled.

**Comment by KevinCCheng** [comment]
Linking
