### ISSUE TITLE
Important info when using array adapters

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#65]
@JoetheSoda. When you use my array adapters, make sure in your java code, don't edit my code, to set the visibility of the container (i.e. lifestyle for reminders and reminder for notifications) fields to GONE. I can show you how to do this if you have any questions.

**Comment by JDNdeveloper** [comment]
More details: Set "@+id/rowNotificationContainerReminder" to GONE visibility and "@+id/rowReminderContainerLifestyle" to GONE visibility. Do this in your java code, aka create objects in the code and use findViewById to get these, then do blah.setVisibility(View.GONE);

**Comment by JDNdeveloper** [comment]
This was never implemented josh.

**Comment by JoetheSoda** [comment]
In maim onResume

**Comment by JDNdeveloper** [comment]
Done.
