### ISSUE TITLE
Create Sprint 2 Report 

### ISSUE THREAD

**Issue by agonza26** [JDNdeveloper/Off-By-One#75]
https://docs.google.com/a/ucsc.edu/document/d/1Tv4T-78GXw21DUZSE3xVLeZJphnJhofDShOTZaCTl70/edit

https://docs.google.com/a/ucsc.edu/document/d/1bJewYPS8IPAOUOVb0ps-Ozg3luH1uN5IhTwvjAy1kL8/edit

**Comment by JDNdeveloper** [comment]
There is no sprint 2 report yet to revise.

**Comment by JDNdeveloper** [comment]
It hasn't been assigned so I just put you in charge and you can assign it to the proper person.

**Comment by agonza26** [comment]
completed thursday, forgot to close
