### ISSUE TITLE
Revise Draft User doc

### ISSUE THREAD

**Issue by agonza26** [JDNdeveloper/Off-By-One#78]
We can both work on this, I believe this will be everything the user might want to see/get understanding of when being presented with the app. We can discuss exactly what this document is in our meeting

**Comment by KevinCCheng** [comment]
Draft documentation mainly completed. Old content in the last two pages of the document. 

Please Verify the contents of the documentation.

**Comment by agonza26** [comment]
completed additions/edits/review of User Doc
