### ISSUE TITLE
Commit all documents to repo Thursday morning

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#84]

**Comment by agonza26** [comment]
I emailed stan to double check that it is thursday morning, Ill update this once I find out

**Comment by JDNdeveloper** [comment]
What to publish:
1. All 3 burnup charts.
2. All 3 scrum boards.
3. Sprint 1 Reflection Report revised
4. Sprint 2 Report
5. Sprint 3 Plan
6. Revised Release Plan
7. Revised User Documentation
8. Test Plan
9. Expanded User Stories

@agonza26, is this correct?

**Comment by JDNdeveloper** [comment]
Done.
