### ISSUE TITLE
Work on burn-up charts to meet Stan's specs

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#86]

**Comment by JDNdeveloper** [comment]
Currently the top line isn't flat like it's supposed to be.

**Comment by KevinCCheng** [comment]
Define "isn't flat"

**Comment by JDNdeveloper** [comment]
Read Stan's email. The blue line should be a flat horizontal line aka slope
0. It currently is a line with a slope that isn't 0.

**Comment by KevinCCheng** [comment]
Corrected

**Comment by JDNdeveloper** [comment]
Kevin, did you read the rest of the email? We also need more data points in
Sprint 2 chart. Did you do this as well?

**Comment by JDNdeveloper** [comment]
The sprint 2 chart doesn't have more data points like it should. So I reopened this issue.

**Comment by KevinCCheng** [comment]
1st thing: I did not create that SCRUM Burnup Sheet

2nd thing: the ticket did not specify which SCRUM burnup sheet

3rd thing: I did not even get the email. 

5th thing: The Burnup chart is supposed DONE BY THE SCRUM MASTER.  I am not the SCRUM master for sprint 2.

**Comment by KevinCCheng** [comment]
Now check it, since I inflated random points on the Sprint 2 chart

**Comment by JDNdeveloper** [comment]
Kevin...I'm not the scrum master. If you have an issue with your assigned
task bring it up with Alex. I was not aware that you did not receive Stan's
email.

Also, I worked on all 3 scrum boards last night even though I haven't been
scrum master even once. You just have to get stuff done sometimes even if
it's not your original role.

When it says work on Burn-Up charts it applies to all three charts.

I will forward you Stan's email.

**Comment by KevinCCheng** [comment]
All three SCRUM burn charts are reflected with the scrum board..

**Comment by KevinCCheng** [comment]
Had alex check on the Burnup chart and did not see any issues. and since there is no response, closing ticket
