### ISSUE TITLE
In DeleteABE, if Notification, remove alarm so alarm doesn't go off anymore

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#92]

**Comment by JohnGemignani** [comment]
This is not storages responsibility. Delete button should save alarm to remove and upon successful deletion it should cancel it. Storage is just storage.

**Comment by JDNdeveloper** [comment]
John, I have a remove alarm function. Just call it in delete.

**Comment by JDNdeveloper** [comment]
Delete happens in multiple places. It would be much easier if your function handles this.

**Comment by JDNdeveloper** [comment]
There's a fundamental reason why this needs to be handled in your delete function: recursion. If you were to delete a reminder, all corresponding notifications would need to be deleted. In deleting them it would be done through your function, not through the delete button listener, and thus your delete function needs to call the remove alarm functions for each notification. The same is true for deleting a Lifestyle. Let me know if you disagree with this statement. If you do disagree, you can re-assign this issue to me and we'll discuss it on Monday.

**Comment by JohnGemignani** [comment]
Put, in ABE a method called, destroy or finish or delete or shutdown. What ever sounds like a good name.

Override it in notification to do whatever object specific cleanups are necessary. Or overload and super the base class. The later is probably better.

Then I can call this method against all ABE children and do any kind of cleanups without knowing anything or doing anything specific.

**Comment by JDNdeveloper** [comment]
That sounds like a good idea. Can you implement that in the ABE objects?

**Comment by JDNdeveloper** [comment]
Please don't assign this to me.

**Comment by JDNdeveloper** [comment]
I'm closing this one and opening two more more descriptive tickets. One for John and one for me.
